config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    root 'welcomes#index'
    get "/checkout" => "welcomes#checkout_page", as: "checkout"
    post "/make_payment" => "welcomes#make_payment", as: "make_payment"
    post "/check_payment_status/:id" => "welcomes#check_payment_status"

    post "/await_payment_response_backend/:id" => "welcomes#await_payment_response_backend", as: "await_payment_response_backend"
    get "/await_payment_response/:id" => "welcomes#await_payment_response", as: "await_payment_response"
    get "/payment_response_success/:id" => "welcomes#payment_response_success", as: "payment_response_success"
    get "/payment_response_fail/:id" => "welcomes#payment_response_fail", as: "payment_response_fail"

    resources :payments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates :billplz_id, uniqueness: true, allow_blank: true
    enum payment_status: [:unknown, :success, :failure]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all.order("id ASC")
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:payment_status, :details)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
    require 'net/http'
    before_action :set_payment, except: [:index, :checkout_page, :make_payment]
    skip_before_action :verify_authenticity_token, :only => [:await_payment_response_backend]
    before_action :set_api

    def index        
    end

    def checkout_page
    end

    def make_payment
        @payment = Payment.create()
        req = Faraday.new do |f|
            f.adapter :net_http
        end

        req = req.post(
            "#{@api_url}api/v3/bills?auto_submit=true", 
            {
                "collection_id": @collection_id,
                "email": "kliwaru@gmail.com",
                "name": "Leon",
                "amount": 200,
                "description": "TEST.",
                "callback_url": "https://billplz-test.herokuapp.com/await_payment_response_backend/#{@payment.id}",
                "redirect_url": "https://billplz-test.herokuapp.com/await_payment_response/#{@payment.id}",
            }.to_json,
            {
                "Authorization" => "Basic #{Base64.encode64(@api_key).chomp}",
                "Content-Type" => "application/json"
            }
        )

        if req.status == 200
            server_resp = JSON.parse(req.body)
            @payment.update(billplz_id: server_resp["id"])
            redirect_to server_resp["url"]
        else
            notice = "SOMETHING WENT WRONG!"
            redirect_to root_path
        end
    end

    # callback_url for billplz
    def await_payment_response_backend 
        @payment.update(details: params)
        if params["paid"] == "true"
            @payment.update(payment_status: "success")
        end
    end

    # redirect url
    def await_payment_response
    end

    # from frontend AJAX
    def check_payment_status
        render :json => { status: @payment.payment_status }
    end

    def payment_response_success
    end

    def payment_response_fail
    end
    
    private
    def set_payment
        @payment = Payment.find(params[:id])
    end

    def set_api
        @api_url = "https://www.billplz-sandbox.com/"
        @api_key = "8a2ab22b-6bea-41ac-a132-10ad130a5712:"
        @collection_id ="g3ttovrw"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillplzTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>

    <br><br><br>
    <hr>
    <%= link_to "Home", root_path %><br>
    <%= link_to "Payment Index", payments_path %><br>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payment_status %>
    <%= form.number_field :payment_status %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table border="1">
    <thead>
        <tr>
            <th>ID</th>
            <th>Billplz ID</th>
            <th>X Signature</th>
            <th>Payment status</th>
            <th>Details</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @payments.each do |payment| %>
            <tr>
                <td><%= payment.id %></td>
                <td><%= payment.billplz_id %></td>
                <td><%= payment.x_signature %></td>
                <td><%= payment.payment_status %></td>
                <td><%= payment.details %></td>
                <td><%= link_to 'Show', payment %></td>
                <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
                <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment status:</strong>
  <%= @payment.payment_status %>
</p>

<p>
  <strong>Details:</strong>
  <%= @payment.details %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/welcomes/await_payment_response.html.erb
<h1>Await Payment Response</h1>
<h3>Bill ID: <%= @payment.id %></h3>

<div>
    <i>View Order Summaries</i>
    <p>blabla..</p>
    <p>blabla..</p>
    <p>blabla..</p>
</div>


<script>
    function checkPaymentStatus(id) {
        $.ajax({
            url: `/check_payment_status/${id}`,
            method: "POST",
            success: function(result){
                console.log('Check Payment Status ' + Date(Date.now()).toString());
                console.log(result["status"]);

                if (result["status"] == "success") {
                    location.replace(`/payment_response_success/${id}`);
                } else if (result["status"] == "failure") {
                    location.replace(`/payment_response_fail/${id}`);
                } else {
                    setTimeout(() => {
                        checkPaymentStatus(id);
                    }, 2000);
                }
            },
            error: function(error){
                console.log('Loop fail');
                console.log(error);
            }
        });
    }

    $(document).ready(() => {
        checkPaymentStatus(<%= @payment.id %>);
    });
</script>

app/views/welcomes/checkout_page.html.erb
<h1>Checkout Page</h1>

<div>
    <i>View Order Summaries</i>
    <p>blabla..</p>
    <p>blabla..</p>
    <p>blabla..</p>
</div>
<br>
<%= button_to "Make Payment", make_payment_path %>

app/views/welcomes/index.html.erb
<h1>BillPLZ Test</h1>
<%= button_to "Checkout Cart", checkout_path, method: :get %>

<br><br>
<h3>Payment Flow</h3>

<p>
    <strong>User Clicks "Checkout Cart"</strong>
    <br>GET welcomes#checkout_page
    <br>Controller creates new payment with order details
    <br>User redirected to checkout page to confirm order details & make payment
</p>

<p>
    <strong>User clicks "Make Payment"</strong>
    <br>Passes to Billplz handling
</p>

<div class="two columns">
    <div>
        <p>
            <strong>User makes Payment w Billplz</strong>
            <br>Billplz communicates with my backend
            <br>GET welcomes#await_payment_response_backend    
        </p>
    </div>
    <div>
        <p>
            <strong>User redirected to "Await payment response" page</strong>
            <br>GET welcomes#await_payment_response to update bill payment status
            <br>on page load, Recursive JS runs AJAX to check backend of payment status update to determine redirect
            <br>AJAX Calls to welcomes#check_payment_status
        </p>
    </div>
</div>

<div class="two columns">
    <div>
        <strong>Payment Success</strong>
    </div>
    <div>
        <strong>Payment Error</strong>
    </div>
</div>

app/views/welcomes/payment_response_fail.html.erb
<h1>Payment Response FAIL</h1>

<div>
    <%= @response %>
</div>

<br><br>
<%= button_to "Try Payment Again", payment_path %>

<br><br>
<%= link_to "Home", root_path %>

app/views/welcomes/payment_response_success.html.erb
<h1>Payment Response SUCCESS</h1>

<div>
    <%= @response %>
</div>

<br><br>
<%= link_to "Home", root_path %>